### ISSUE TITLE
Shortcuts in b. 3143

### ISSUE THREAD

**Issue by JackGin** [randy3k/LaTeXYZ#10]
After recent Sublime upgrade to b. 3143, the \` to \`' auto completion in LaTeXTools was re-enabled, killing shortcuts starting with `. This can be fixed by hand in the LaTeXTools settings, but I wonder whether it is possible to fine-tune the LaTeXYZ to take care of it automatically?

**Comment by randy3k** [comment]
Which LaTeXTools setting are you referring to?

**Comment by JackGin** [comment]
I have to comment out the "autopair quotation marks (`')" section of the LaTeX Package keymap for Linux, located at /.config/sublime-text-3/Packages/LaTeXTools/Default (Linux).sublime-keymap

**Comment by randy3k** [comment]
I have no issues of using for example <kbd>`a</kbd> in the math environment. Are you sure that you are using those keybinds in the math environment? What version of LaTeXTools and LaTeXYZ are you using?

**Comment by JackGin** [comment]
Yeah, I am sure.
3.14.2 and 0.1.8, respectively.
The shortcut \`a works in the math mode only when I manually comment the autopair quotation marks \`'  section of the aforementioned file. Otherwise as soon as I type \` I get the auto-completed  \`'.

**Comment by randy3k** [comment]
It is because LaTeXYZ is loaded before LaTeXTools. 0fe0f8dcf6c962f6ea7f3a0004848d537243258c should fix it.

**Comment by randy3k** [comment]
0.1.9 is coming soon.
