### ISSUE TITLE
tab completion does not work correctly after upgrade to ST4

### ISSUE THREAD

**Issue by aaltland** [randy3k/LaTeXYZ#26]
Autocompletions triggered by tab-tab no longer work as they should after upgrading to ST4 (build 4107 on macos). Say, a \rightarrow used to be generated by "-> + tab + tab". What I get now is "->\rightarrow", i.e. the triggering symbols "->" aren't deleted. Any ideas?

**Comment by MariusNielsen** [comment]
Did you ever find a solution? I am having same kinds of trouble.

**Comment by aaltland** [comment]
Nope, nobody replied. I fear that latextools is discontinued. They used to reply in no time. Seems to be dead. Pity.

**Comment by randy3k** [comment]
Sorry for the late reply. I could verify that it is broken. Auto completion in ST 4 works a bit differently, the new `auto_complete` doesn't commit the best completion now. We probably need to write a custom command for the arrow completion.

**Comment by aaltland** [comment]
Ah, thanks. Having this issue fixed would be helpful, indeed.

**Comment by randy3k** [comment]
0.1.17 should fix it.

**Comment by aaltland** [comment]
Cool, thanks!! A.
