### ISSUE TITLE
Sublime Text 4 Incorrect Autocomplete Behavior

### ISSUE THREAD

**Issue by mschmidt271** [randy3k/LaTeXYZ#27]
It appears that certain autocompletions operate incorrectly since the upgrade to Sublime 4, and it seems to be when the autocompletion takes two arguments. The behavior is that the command loses the leading backslash.

For example,  with tab completion on, typing `\frac + tab` gives `frac{}{}` and the same is true for `\sum + tab` yielding `sum_{}^{}`.

**Comment by randy3k** [comment]
Did you have `LaTeX-cwl` installed? `LaTeXYZ` doesn't provide any autocompletion if it is installed.

https://github.com/SublimeText/LaTeXTools/issues/1524

**Comment by mschmidt271** [comment]
I did not have `LaTeX-cwl` installed, but strangely, after installing I'm seeing the same behavior. And I have applied the comment patch described in the `LaTeXTools` issue you linked, which helps with many completions, but still not things like `\frac{}{}` and `sum_{}^{}`. Am I correct in my understanding that those completions come from `LaTeXYZ` and not `LaTeXTools` or `LaTeX-cwl`?

**Comment by randy3k** [comment]
Oh. My bad, I just forgot to make a new release for ST4. The `master` branch should be working just fine.

**Comment by mschmidt271** [comment]
Thanks for getting to that! I added the package from master. However, it looks like the functionality I mention above is gone now. e.g., `\sum + tab` now completes to `\sup` and `\frac + tab` completes to `\frac   `  with the spaces from the tab. Maybe this functionality has just gone away? Loved those completions but get it if this is becoming a pain 🙃

**Comment by randy3k** [comment]
Maybe because of LaTeX-cwl? It still works for me.
![Screen Shot 2021-06-09 at 12 54 51 PM](https://user-images.githubusercontent.com/1690993/121420429-ea7b8780-c921-11eb-8ff6-1fb23f7c406d.png)

**Comment by mschmidt271** [comment]
Turns out I had to restart ST and works now 🤦🏻‍♂️.

Thanks for all the help!
