### ISSUE TITLE
Include DeclarePairedDelimiterX in preamble

### ISSUE THREAD

**Issue by musm** [randy3k/LaTeXYZ#5]
![image](https://cloud.githubusercontent.com/assets/4319522/25559383/ac38a70c-2d06-11e7-83f1-d46de4f76383.png)

would be nice if I could get these to also be included (from mathtools package)

**Comment by randy3k** [comment]
Note to myself. The syntax is

```
\DeclarePairedDelimiter{〈cmd〉}{〈left_delim〉}{〈right_delim〉}
\DeclarePairedDelimiterX{〈cmd〉}[1]{〈left_delim〉}{〈right_delim〉}{#1}
```

**Comment by musm** [comment]
stale
