### ISSUE TITLE
Tab jumping out of parens not working?

### ISSUE THREAD

**Issue by pluskid** [randy3k/LaTeXYZ#6]
First I'd like to thank you for creating LaTeXBox which has been tremendously useful for me. I recently migrated to LaTeXTools as suggested by the LaTeXBox README. And then installed LaTeXYZ when I found the shortcuts for math symbols are missing. 

Everything works smoothly except that I noticed that I can no longer jump out of parens using TAB. For example, if I'm in math mode, and press `(`, I will get auto completed a pair `(|)` where `|` is the cursor. However, if I press TAB, instead of jumping out of the parens, it just insert a TAB. Is there anything that I could do to diagnose and fix this? Thank you very much!

**Comment by randy3k** [comment]
Check the option `auto_create_fields`. The default is set  as false as most LaTeXTools users may not like this.

**Comment by pluskid** [comment]
Superb! Thanks!
